package modelo_hbm;
// Generated 01-jun-2017 11:44:50 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Acciones generated by hbm2java
 */
public class Acciones  implements java.io.Serializable {


     private Integer idAcciones;
     private String nombre;
     private String descripcion;
     private String ruta;
     private Set permisoses = new HashSet(0);

    public Acciones() {
    }

	
    public Acciones(String nombre, String descripcion, String ruta) {
        this.nombre = nombre;
        this.descripcion = descripcion;
        this.ruta = ruta;
    }
    public Acciones(String nombre, String descripcion, String ruta, Set permisoses) {
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.ruta = ruta;
       this.permisoses = permisoses;
    }
   
    public Integer getIdAcciones() {
        return this.idAcciones;
    }
    
    public void setIdAcciones(Integer idAcciones) {
        this.idAcciones = idAcciones;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getRuta() {
        return this.ruta;
    }
    
    public void setRuta(String ruta) {
        this.ruta = ruta;
    }
    public Set getPermisoses() {
        return this.permisoses;
    }
    
    public void setPermisoses(Set permisoses) {
        this.permisoses = permisoses;
    }




}


