package modelo_hbm;
// Generated 01-jun-2017 11:44:50 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Almacen generated by hbm2java
 */
public class Almacen  implements java.io.Serializable {


     private long nit;
     private String nombre;
     private Set empleadoses = new HashSet(0);
     private Set pedidoses = new HashSet(0);

    public Almacen() {
    }

	
    public Almacen(long nit, String nombre) {
        this.nit = nit;
        this.nombre = nombre;
    }
    public Almacen(long nit, String nombre, Set empleadoses, Set pedidoses) {
       this.nit = nit;
       this.nombre = nombre;
       this.empleadoses = empleadoses;
       this.pedidoses = pedidoses;
    }
   
    public long getNit() {
        return this.nit;
    }
    
    public void setNit(long nit) {
        this.nit = nit;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getEmpleadoses() {
        return this.empleadoses;
    }
    
    public void setEmpleadoses(Set empleadoses) {
        this.empleadoses = empleadoses;
    }
    public Set getPedidoses() {
        return this.pedidoses;
    }
    
    public void setPedidoses(Set pedidoses) {
        this.pedidoses = pedidoses;
    }




}


