package modelo_hbm;
// Generated 18-may-2017 15:31:17 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cargos generated by hbm2java
 */
public class Cargos  implements java.io.Serializable {


     private Integer idCargo;
     private String nombre;
     private Set empleadoses = new HashSet(0);

    public Cargos() {
    }

	
    public Cargos(String nombre) {
        this.nombre = nombre;
    }
    public Cargos(String nombre, Set empleadoses) {
       this.nombre = nombre;
       this.empleadoses = empleadoses;
    }
   
    public Integer getIdCargo() {
        return this.idCargo;
    }
    
    public void setIdCargo(Integer idCargo) {
        this.idCargo = idCargo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getEmpleadoses() {
        return this.empleadoses;
    }
    
    public void setEmpleadoses(Set empleadoses) {
        this.empleadoses = empleadoses;
    }




}


