package modelo_hbm;
// Generated 18-may-2017 15:31:17 by Hibernate Tools 4.3.1



/**
 * DetalleFacturasId generated by hbm2java
 */
public class DetalleFacturasId  implements java.io.Serializable {


     private int idDetalleFactura;
     private int numFactura;

    public DetalleFacturasId() {
    }

    public DetalleFacturasId(int idDetalleFactura, int numFactura) {
       this.idDetalleFactura = idDetalleFactura;
       this.numFactura = numFactura;
    }
   
    public int getIdDetalleFactura() {
        return this.idDetalleFactura;
    }
    
    public void setIdDetalleFactura(int idDetalleFactura) {
        this.idDetalleFactura = idDetalleFactura;
    }
    public int getNumFactura() {
        return this.numFactura;
    }
    
    public void setNumFactura(int numFactura) {
        this.numFactura = numFactura;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DetalleFacturasId) ) return false;
		 DetalleFacturasId castOther = ( DetalleFacturasId ) other; 
         
		 return (this.getIdDetalleFactura()==castOther.getIdDetalleFactura())
 && (this.getNumFactura()==castOther.getNumFactura());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdDetalleFactura();
         result = 37 * result + this.getNumFactura();
         return result;
   }   


}


