package modelo_hbm;
// Generated 01-jun-2017 11:44:50 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Facturas generated by hbm2java
 */
public class Facturas  implements java.io.Serializable {


     private Integer numFactura;
     private Clientes clientes;
     private Empleados empleados;
     private ModoPago modoPago;
     private Date fecha;
     private Set detalleFacturases = new HashSet(0);

    public Facturas() {
    }

	
    public Facturas(Clientes clientes, Empleados empleados, Date fecha) {
        this.clientes = clientes;
        this.empleados = empleados;
        this.fecha = fecha;
    }
    public Facturas(Clientes clientes, Empleados empleados, ModoPago modoPago, Date fecha, Set detalleFacturases) {
       this.clientes = clientes;
       this.empleados = empleados;
       this.modoPago = modoPago;
       this.fecha = fecha;
       this.detalleFacturases = detalleFacturases;
    }
   
    public Integer getNumFactura() {
        return this.numFactura;
    }
    
    public void setNumFactura(Integer numFactura) {
        this.numFactura = numFactura;
    }
    public Clientes getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Clientes clientes) {
        this.clientes = clientes;
    }
    public Empleados getEmpleados() {
        return this.empleados;
    }
    
    public void setEmpleados(Empleados empleados) {
        this.empleados = empleados;
    }
    public ModoPago getModoPago() {
        return this.modoPago;
    }
    
    public void setModoPago(ModoPago modoPago) {
        this.modoPago = modoPago;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Set getDetalleFacturases() {
        return this.detalleFacturases;
    }
    
    public void setDetalleFacturases(Set detalleFacturases) {
        this.detalleFacturases = detalleFacturases;
    }




}


