package modelo_hbm;
// Generated 01-jun-2017 11:44:50 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Marcas generated by hbm2java
 */
public class Marcas  implements java.io.Serializable {


     private Integer idMarcas;
     private String nombre;
     private Set productoses = new HashSet(0);

    public Marcas() {
    }

	
    public Marcas(String nombre) {
        this.nombre = nombre;
    }
    public Marcas(String nombre, Set productoses) {
       this.nombre = nombre;
       this.productoses = productoses;
    }
   
    public Integer getIdMarcas() {
        return this.idMarcas;
    }
    
    public void setIdMarcas(Integer idMarcas) {
        this.idMarcas = idMarcas;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getProductoses() {
        return this.productoses;
    }
    
    public void setProductoses(Set productoses) {
        this.productoses = productoses;
    }




}


