package modelo_hbm;
// Generated 01-jun-2017 11:44:50 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ModoPago generated by hbm2java
 */
public class ModoPago  implements java.io.Serializable {


     private Integer idModoPago;
     private String nombre;
     private Set pedidoses = new HashSet(0);
     private Set facturases = new HashSet(0);

    public ModoPago() {
    }

	
    public ModoPago(String nombre) {
        this.nombre = nombre;
    }
    public ModoPago(String nombre, Set pedidoses, Set facturases) {
       this.nombre = nombre;
       this.pedidoses = pedidoses;
       this.facturases = facturases;
    }
   
    public Integer getIdModoPago() {
        return this.idModoPago;
    }
    
    public void setIdModoPago(Integer idModoPago) {
        this.idModoPago = idModoPago;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getPedidoses() {
        return this.pedidoses;
    }
    
    public void setPedidoses(Set pedidoses) {
        this.pedidoses = pedidoses;
    }
    public Set getFacturases() {
        return this.facturases;
    }
    
    public void setFacturases(Set facturases) {
        this.facturases = facturases;
    }




}


