package modelo_hbm;
// Generated 18-may-2017 15:31:17 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Pedidos generated by hbm2java
 */
public class Pedidos  implements java.io.Serializable {


     private Integer numPedido;
     private Almacen almacen;
     private ModoPago modoPago;
     private Proveedores proveedores;
     private Date fecha;
     private Set detallePedidoses = new HashSet(0);

    public Pedidos() {
    }

	
    public Pedidos(Almacen almacen, ModoPago modoPago, Proveedores proveedores, Date fecha) {
        this.almacen = almacen;
        this.modoPago = modoPago;
        this.proveedores = proveedores;
        this.fecha = fecha;
    }
    public Pedidos(Almacen almacen, ModoPago modoPago, Proveedores proveedores, Date fecha, Set detallePedidoses) {
       this.almacen = almacen;
       this.modoPago = modoPago;
       this.proveedores = proveedores;
       this.fecha = fecha;
       this.detallePedidoses = detallePedidoses;
    }
   
    public Integer getNumPedido() {
        return this.numPedido;
    }
    
    public void setNumPedido(Integer numPedido) {
        this.numPedido = numPedido;
    }
    public Almacen getAlmacen() {
        return this.almacen;
    }
    
    public void setAlmacen(Almacen almacen) {
        this.almacen = almacen;
    }
    public ModoPago getModoPago() {
        return this.modoPago;
    }
    
    public void setModoPago(ModoPago modoPago) {
        this.modoPago = modoPago;
    }
    public Proveedores getProveedores() {
        return this.proveedores;
    }
    
    public void setProveedores(Proveedores proveedores) {
        this.proveedores = proveedores;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Set getDetallePedidoses() {
        return this.detallePedidoses;
    }
    
    public void setDetallePedidoses(Set detallePedidoses) {
        this.detallePedidoses = detallePedidoses;
    }




}


