package modelo_hbm;
// Generated 01-jun-2017 11:44:50 by Hibernate Tools 4.3.1



/**
 * Permisos generated by hbm2java
 */
public class Permisos  implements java.io.Serializable {


     private Integer idPermisos;
     private Acciones acciones;
     private Roles roles;

    public Permisos() {
    }

    public Permisos(Acciones acciones, Roles roles) {
       this.acciones = acciones;
       this.roles = roles;
    }
   
    public Integer getIdPermisos() {
        return this.idPermisos;
    }
    
    public void setIdPermisos(Integer idPermisos) {
        this.idPermisos = idPermisos;
    }
    public Acciones getAcciones() {
        return this.acciones;
    }
    
    public void setAcciones(Acciones acciones) {
        this.acciones = acciones;
    }
    public Roles getRoles() {
        return this.roles;
    }
    
    public void setRoles(Roles roles) {
        this.roles = roles;
    }




}


