package modelo_hbm;
// Generated 18-may-2017 15:31:17 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Roles generated by hbm2java
 */
public class Roles  implements java.io.Serializable {


     private Integer idRoles;
     private String nombre;
     private String descripcion;
     private Set permisoses = new HashSet(0);
     private Set usuariosRoleses = new HashSet(0);

    public Roles() {
    }

	
    public Roles(String nombre, String descripcion) {
        this.nombre = nombre;
        this.descripcion = descripcion;
    }
    public Roles(String nombre, String descripcion, Set permisoses, Set usuariosRoleses) {
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.permisoses = permisoses;
       this.usuariosRoleses = usuariosRoleses;
    }
   
    public Integer getIdRoles() {
        return this.idRoles;
    }
    
    public void setIdRoles(Integer idRoles) {
        this.idRoles = idRoles;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getPermisoses() {
        return this.permisoses;
    }
    
    public void setPermisoses(Set permisoses) {
        this.permisoses = permisoses;
    }
    public Set getUsuariosRoleses() {
        return this.usuariosRoleses;
    }
    
    public void setUsuariosRoleses(Set usuariosRoleses) {
        this.usuariosRoleses = usuariosRoleses;
    }




}


