package modelo_hbm;
// Generated 01-jun-2017 11:44:50 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Roles generated by hbm2java
 */
public class Roles  implements java.io.Serializable {


     private Integer idRoles;
     private String nombre;
     private String clave;
     private Set permisoses = new HashSet(0);
     private Set usuariosRoleses = new HashSet(0);

    public Roles() {
    }

	
    public Roles(String nombre, String clave) {
        this.nombre = nombre;
        this.clave = clave;
    }
    public Roles(String nombre, String clave, Set permisoses, Set usuariosRoleses) {
       this.nombre = nombre;
       this.clave = clave;
       this.permisoses = permisoses;
       this.usuariosRoleses = usuariosRoleses;
    }
   
    public Integer getIdRoles() {
        return this.idRoles;
    }
    
    public void setIdRoles(Integer idRoles) {
        this.idRoles = idRoles;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }
    public Set getPermisoses() {
        return this.permisoses;
    }
    
    public void setPermisoses(Set permisoses) {
        this.permisoses = permisoses;
    }
    public Set getUsuariosRoleses() {
        return this.usuariosRoleses;
    }
    
    public void setUsuariosRoleses(Set usuariosRoleses) {
        this.usuariosRoleses = usuariosRoleses;
    }




}


