package modelo_hbm;
// Generated 01-jun-2017 11:44:50 by Hibernate Tools 4.3.1



/**
 * UsuariosRolesId generated by hbm2java
 */
public class UsuariosRolesId  implements java.io.Serializable {


     private int idUsuariosRoles;
     private int idRol;
     private int idUsers;

    public UsuariosRolesId() {
    }

    public UsuariosRolesId(int idUsuariosRoles, int idRol, int idUsers) {
       this.idUsuariosRoles = idUsuariosRoles;
       this.idRol = idRol;
       this.idUsers = idUsers;
    }
   
    public int getIdUsuariosRoles() {
        return this.idUsuariosRoles;
    }
    
    public void setIdUsuariosRoles(int idUsuariosRoles) {
        this.idUsuariosRoles = idUsuariosRoles;
    }
    public int getIdRol() {
        return this.idRol;
    }
    
    public void setIdRol(int idRol) {
        this.idRol = idRol;
    }
    public int getIdUsers() {
        return this.idUsers;
    }
    
    public void setIdUsers(int idUsers) {
        this.idUsers = idUsers;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UsuariosRolesId) ) return false;
		 UsuariosRolesId castOther = ( UsuariosRolesId ) other; 
         
		 return (this.getIdUsuariosRoles()==castOther.getIdUsuariosRoles())
 && (this.getIdRol()==castOther.getIdRol())
 && (this.getIdUsers()==castOther.getIdUsers());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdUsuariosRoles();
         result = 37 * result + this.getIdRol();
         result = 37 * result + this.getIdUsers();
         return result;
   }   


}


