/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import Correo.ControladorCorreo;
import Correo.Correo;
import dao_Impl.DAOUsuarioImpl;
import dao_Impl.DAOUsuario_RolImpl;
import interfaces_dao.DAOUsuario;
import interfaces_dao.DAOUsuario_Rol;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modelo_dao.Usuario;
import mysql_conexion.CargaRol;
import mysql_conexion.Rol;
import validaciones.Login;
import validaciones.RegistroUser;
import static ventanas.Main_Prueba_dao.c;

/**
 *
 * @author breiner
 */
public class VUsuario extends javax.swing.JFrame {

    Correo c = new Correo();
    
    public VUsuario() {
        initComponents();
        pnl_1.setBackground(new Color(0,0,0,195));
        setResizable(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_2 = new javax.swing.JPanel();
        txt_NombreU = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        txt_EmailU = new javax.swing.JTextField();
        txt_PassU = new javax.swing.JPasswordField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        btn_Registrar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        Roles_Cbox = new javax.swing.JComboBox<>();
        jSeparator4 = new javax.swing.JSeparator();
        btn_Home = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txt_PassU1 = new javax.swing.JPasswordField();
        jSeparator5 = new javax.swing.JSeparator();
        pnl_1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl_2.setBackground(new java.awt.Color(32, 33, 35));
        pnl_2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_NombreU.setBackground(new java.awt.Color(32, 33, 35));
        txt_NombreU.setForeground(new java.awt.Color(204, 204, 204));
        txt_NombreU.setBorder(null);
        txt_NombreU.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_NombreU.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_NombreUFocusGained(evt);
            }
        });
        txt_NombreU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NombreUActionPerformed(evt);
            }
        });
        pnl_2.add(txt_NombreU, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 280, 20));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        pnl_2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 280, 10));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        pnl_2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 280, 10));

        txt_EmailU.setBackground(new java.awt.Color(32, 33, 35));
        txt_EmailU.setForeground(new java.awt.Color(204, 204, 204));
        txt_EmailU.setBorder(null);
        txt_EmailU.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_EmailU.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_EmailUFocusGained(evt);
            }
        });
        txt_EmailU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_EmailUActionPerformed(evt);
            }
        });
        pnl_2.add(txt_EmailU, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 280, 20));

        txt_PassU.setBackground(new java.awt.Color(32, 33, 35));
        txt_PassU.setForeground(new java.awt.Color(204, 204, 204));
        txt_PassU.setBorder(null);
        txt_PassU.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_PassUFocusGained(evt);
            }
        });
        pnl_2.add(txt_PassU, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 280, -1));

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        pnl_2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 280, 10));

        jLabel3.setForeground(new java.awt.Color(52, 52, 54));
        jLabel3.setText("Correo");
        pnl_2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, -1, -1));

        btn_Registrar.setBackground(new java.awt.Color(126, 87, 194));
        btn_Registrar.setFont(new java.awt.Font("NanumMyeongjo", 1, 12)); // NOI18N
        btn_Registrar.setForeground(new java.awt.Color(255, 255, 255));
        btn_Registrar.setText("Registrar");
        btn_Registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RegistrarActionPerformed(evt);
            }
        });
        pnl_2.add(btn_Registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 440, 280, 40));

        jLabel4.setForeground(new java.awt.Color(52, 52, 54));
        jLabel4.setText("Contraseña");
        pnl_2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, -1, -1));

        jLabel10.setForeground(new java.awt.Color(57, 113, 177));
        jLabel10.setText("Usuario");
        pnl_2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, -1, -1));

        jLabel13.setForeground(new java.awt.Color(52, 52, 54));
        jLabel13.setText("Nombre");
        pnl_2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, -1, -1));

        Roles_Cbox.setBackground(new java.awt.Color(32, 33, 35));
        Roles_Cbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione..", "root", "admin", "cajero" }));
        Roles_Cbox.setBorder(null);
        Roles_Cbox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Roles_CboxFocusGained(evt);
            }
        });
        pnl_2.add(Roles_Cbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, -1, -1));

        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        pnl_2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 280, 10));

        btn_Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/home1.png"))); // NOI18N
        btn_Home.setBorder(null);
        btn_Home.setBorderPainted(false);
        btn_Home.setContentAreaFilled(false);
        btn_Home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Home.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_Home.setIconTextGap(-3);
        btn_Home.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_HomeActionPerformed(evt);
            }
        });
        pnl_2.add(btn_Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 0, 30, 30));

        jLabel5.setForeground(new java.awt.Color(52, 52, 54));
        jLabel5.setText("Confirmar Contraseña");
        pnl_2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, -1, -1));

        txt_PassU1.setBackground(new java.awt.Color(32, 33, 35));
        txt_PassU1.setForeground(new java.awt.Color(204, 204, 204));
        txt_PassU1.setBorder(null);
        txt_PassU1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_PassU1FocusGained(evt);
            }
        });
        pnl_2.add(txt_PassU1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 280, -1));

        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));
        pnl_2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 280, 10));

        getContentPane().add(pnl_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 560));

        pnl_1.setBackground(new java.awt.Color(0, 0, 0));
        pnl_1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("AngsanaUPC", 3, 90)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(57, 113, 177));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registro");
        pnl_1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 270, 120));

        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("Design, Create Awesome Swing UI");
        pnl_1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, -1, -1));

        getContentPane().add(pnl_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 410, 560));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.jpg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, -1, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_NombreUFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_NombreUFocusGained

        jSeparator1.setBackground(new Color(57,113,177)); // Color de las casillas al precionar
        jLabel13.setForeground(new Color(57,113,177)); // Color de los titulos al precionar
        jLabel3.setForeground(new Color(51,52,54));
        jLabel4.setForeground(new Color(51,52,54));
        jLabel10.setForeground(new Color(51,52,54));
        jLabel5.setForeground(new Color(51,52,54));
    }//GEN-LAST:event_txt_NombreUFocusGained

    private void txt_NombreUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NombreUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NombreUActionPerformed

    private void txt_EmailUFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_EmailUFocusGained

        jSeparator3.setBackground(new Color(57,113,177)); // Color de las casillas al precionar
        jLabel3.setForeground(new Color(57,113,177)); // Color de los titulos al precionar
        jLabel10.setForeground(new Color(51,52,54));
        jLabel4.setForeground(new Color(51,52,54));
        jLabel13.setForeground(new Color(51,52,54));
        jLabel5.setForeground(new Color(51,52,54));
    }//GEN-LAST:event_txt_EmailUFocusGained

    private void txt_EmailUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_EmailUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_EmailUActionPerformed

    private void txt_PassUFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_PassUFocusGained

        jSeparator2.setBackground(new Color(57,113,177)); // Color de las casillas al precionar
        jLabel4.setForeground(new Color(57,113,177)); // Color de los titulos al precionar
        jLabel3.setForeground(new Color(51,52,54));
        jLabel10.setForeground(new Color(51,52,54));
        jLabel13.setForeground(new Color(51,52,54));
        jLabel5.setForeground(new Color(51,52,54));
        //dispose();
    }//GEN-LAST:event_txt_PassUFocusGained

    private void btn_RegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RegistrarActionPerformed
        
        RegistroUser ru = new RegistroUser();
        DAOUsuario user = new DAOUsuarioImpl();
        DAOUsuario_Rol usrl = new DAOUsuario_RolImpl();
        Usuario usr = new Usuario();
        CargaRol cr = new CargaRol();
        Rol rl = new Rol();

        int swUser = 0;
        int swEmail = 0;

        String rolName = (String)Roles_Cbox.getSelectedItem();
        String nombre = txt_NombreU.getText();
        String email = txt_EmailU.getText();
        String pass = String.valueOf(txt_PassU.getPassword());
        String pass1 = String.valueOf(txt_PassU1.getPassword());
        
        if(rolName != "Seleccione.."){
            rl = cr.cargaR(rolName);
            usr.setUsuario(nombre);
            usr.setEmail(email);
            usr.setPass(pass);
            
            swUser = ru.validaUsuario(usr, rl);
            swEmail = ru.validaEmail(usr, rl);
            
            if(swUser != 1 && swEmail != 1 && pass.equals(pass1)){
                try { 
                    user.RegistrarUsuario(usr, rl);
                    usrl.RegistrarUsuarioR(usr, rl);
                    
                    
                    c.setContraseña("ybrsyumnqftsodse");
                    c.setUsuarioCorreo("noj2304@gmail.com");
                    c.setAsunto("Bienvenido a nuestra Empresa");
                    c.setDestino(usr.getEmail());
                    c.setMensaje("Cordial saludo\nEstamos agradecidos por tenerlo en nuestra empresa.\n"
                            + "Le recordamos sus datos:\n"
                            + "Usuario: " +usr.getUsuario()+"\n"
                                    + "Email: "+ usr.getEmail()+"\n"+
                            "Contraseña: "+usr.getPass());
                    c.setNombreArchivo("bienvenido.jpg");
                    c.setRutaArchivo("bienvenido.jpg");

                    ControladorCorreo controlador = new ControladorCorreo();

                    controlador.enviarCorreo(c);
                    
                    
                } catch (Exception ex) {
                    Logger.getLogger(VUsuario.class.getName()).log(Level.SEVERE, null, ex);
                }
            }else if(swUser != 0){
                JOptionPane.showMessageDialog(null, "Por favor intente con otro Usuario", " Usuario no Disponible",NORMAL);
            }else if(swEmail != 0){
                JOptionPane.showMessageDialog(null, "Por favor intente con otro Email", " Email no Disponible",NORMAL);
            }else if(pass != pass1){
                JOptionPane.showMessageDialog(null, "Por favor verifique su contraseña", " Las Contraseñas no Coinciden",NORMAL);
            }
            
        }else{
            JOptionPane.showMessageDialog(null, "Seleccione un tipo de Usuario"," Tipo de Usuario Incorrecto",ICONIFIED);
        }
    }//GEN-LAST:event_btn_RegistrarActionPerformed

    private void Roles_CboxFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Roles_CboxFocusGained
        jSeparator4.setBackground(new Color(57,113,177)); // Color de las casillas al precionar
        jLabel10.setForeground(new Color(57,113,177)); // Color de los titulos al precionar
        jLabel3.setForeground(new Color(51,52,54));
        jLabel4.setForeground(new Color(51,52,54));
        jLabel13.setForeground(new Color(51,52,54));
        jLabel5.setForeground(new Color(51,52,54));
    }//GEN-LAST:event_Roles_CboxFocusGained

    private void btn_HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_HomeActionPerformed
        VLogin lg = new VLogin();
        lg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_HomeActionPerformed

    private void txt_PassU1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_PassU1FocusGained
        jSeparator5.setForeground(new Color(57,113,177));
        jLabel5.setForeground(new Color(57,113,177)); // Color de las casillas al precionar
        jLabel10.setForeground(new Color(51,52,54)); // Color de los titulos al precionar
        jLabel3.setForeground(new Color(51,52,54));
        jLabel4.setForeground(new Color(51,52,54));
        jLabel13.setForeground(new Color(51,52,54));
    }//GEN-LAST:event_txt_PassU1FocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Roles_Cbox;
    private javax.swing.JButton btn_Home;
    private javax.swing.JButton btn_Registrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JPanel pnl_1;
    private javax.swing.JPanel pnl_2;
    public static javax.swing.JTextField txt_EmailU;
    public static javax.swing.JTextField txt_NombreU;
    public static javax.swing.JPasswordField txt_PassU;
    public static javax.swing.JPasswordField txt_PassU1;
    // End of variables declaration//GEN-END:variables
}
